### ISSUE TITLE
"2016 Polling" column

### ISSUE THREAD

**Issue by therealparmesh** [jpangelle/2020-polls#1]
It may be interesting to see 2016 polling alongside 2016 results and 2020 polling.

Great work BTW!

**Comment by jpangelle** [comment]
Thanks Parmesh! Added a column for 2016 polling (9ba18bc). It looks presentable on desktop but now it's looking very cluttered on mobile. Any ideas on how to present this in a compact yet fully visible way?

**Comment by therealparmesh** [comment]
Awesome!

Good question. I wonder if maybe going 1 column with a row for each block is good enough for mobile. Or perhaps having 2 rows would look better - 1 with the polling blocks and 1 with the results block(s).

**Comment by jpangelle** [comment]
I made a compact view for mobile where the states are abbreviated
![image](https://user-images.githubusercontent.com/28536523/98007937-9754bb80-1db9-11eb-80c1-85a60619e5e6.png)
